services:
  backend:
    image: ${DOCKERHUB_USERNAME}/qr-question-backend:latest
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/qr-question-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started
