name: CI - Trigger Jenkins CD

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Jenkins Deployment
        run: |
          echo "🚀 Triggering Jenkins Deployment..."
          curl -X POST "http://${{ secrets.JENKINS_HOST }}:8080/job/${{ secrets.JENKINS_JOB_NAME }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
